apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.15
    max_hamming: 0
    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine_edges: true
      debug: false
    tag:
      ids: [0]
      frames: [""]
      sizes: [0.15]